name: CrazyRunes
author: BadBones69
main: me.BadBones69.CrazyRunes.Main
version: 1.0
description: >
             Plugin with cool runes.
commands:
  Runes:
    description: Opens the Runes GUI.
    aliases: [crazyrunes]